%clic_correction_options_test.m
%permet de modifier les option de recentrage lors de la saisie, le
%deplacement,..., des structures

%si la fenetre est deja ouverte
if isfield(windows,'ClicCorrectionControl')
    figure(windows.ClicCorrectionControl.handle)
    disp('already opened')
    return
end

%% save options in case of cancel
clear option_saved %just in case
option_saved=session.options;
valid_options=0;%si l'utilisateur ferme <=> cancel

%% create the control figure
windows.ClicCorrectionControl.handle=figure(11);
set(windows.ClicCorrectionControl.handle,'units','normalized',...
               'menubar','none',...
               'name','clic corrections',...
               'position',[0.6898    0.3650    0.3031    0.5487],...
               'deletefcn',['if valid_options==1;',...
                               'delete([session.HOME,session.SEP,''profilviewer'',session.SEP,''default_options.mat'']);',...
                               'racine=session.options;',...
                               'save([session.HOME,session.SEP,''profilviewer'',session.SEP,''default_options.mat''],''racine'');',...
                            'else;',...
                               'session.options=option_saved;',...
                           'end;',...
                           'clear option_saved valid_options racine popuplist;',...
                           'windows=rmfield(windows,''ClicCorrectionControl''); '])
           
%% panels and control buttons
%I) ok cancel and help and switchers
windows.ClicCorrectionControl.ok_handle=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'position',[.02,.01,.2,.07],...
    'string','ok',...
    'callback',['valid_options=1;',...
                'close(windows.ClicCorrectionControl.handle);']);

windows.ClicCorrectionControl.cancel_handle=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'position',[.5-.2/2,.01,.2,.07],...
    'string','cancel',...
    'callback',['valid_options=0;',...
                'close(windows.ClicCorrectionControl.handle);']);%attention au deletefcn=clear the saved options

windows.ClicCorrectionControl.help_handle=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'position',[1-.05-.2,.01,.2,.07],...
    'string','help',...
    'callback',['edit ',session.HOME,session.SEP,'help',session.SEP,'clic_correction_options.txt']);



%II) panel for merging options while creating a new structure
windows.ClicCorrectionControl.structurecreation.panelhandle=uipanel(...
    'parent',windows.ClicCorrectionControl.handle,...
    'title','structure creation',...
    'units','normalized',...
    'ForeGroundColor','b',...
    'position',[0,.15,1,1-.25]);

%III) panel for merging options while moving points
windows.ClicCorrectionControl.movingpoints.panelhandle=uipanel(...
    'parent',windows.ClicCorrectionControl.handle,...
    'title','moving points',...
    'units','normalized',...
    'ForeGroundColor',[0 .7 0],...
    'position',[0,.15,1,1-.25],...
    'visible','off');

%IV) switchers, par defaut on est sur creation
windows.ClicCorrectionControl.creation_handle=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'position',[0,.92,.2,.07],...
    'string','creation',...
    'ForeGroundColor','black',...
    'callback',...
        ['set(windows.ClicCorrectionControl.creation_handle,''ForeGroundColor'',''black'');',...
         'set(windows.ClicCorrectionControl.motion_handle,''ForeGroundColor'',[.5 .5 .5]);',...
         'set(windows.ClicCorrectionControl.structurecreation.panelhandle,''visible'',''on'');',...
         'set(windows.ClicCorrectionControl.movingpoints.panelhandle,''visible'',''off'');']);
windows.ClicCorrectionControl.motion_handle=uicontrol(...    
    'style','pushbutton',...
    'units','normalized',...
    'position',[.2,.92,.2,.07],...
    'string','motion',...
    'ForeGroundColor',[.5 .5 .5],...
    'callback',...
        ['set(windows.ClicCorrectionControl.creation_handle,''ForeGroundColor'',[.5 .5 .5]);',...
         'set(windows.ClicCorrectionControl.motion_handle,''ForeGroundColor'',''black'');',...
         'set(windows.ClicCorrectionControl.structurecreation.panelhandle,''visible'',''off'');',...
         'set(windows.ClicCorrectionControl.movingpoints.panelhandle,''visible'',''on'');']);

%V) restauration des parametres par defaut
windows.ClicCorrectionControl.restoredefaults=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'position',[.8,.92,.2,.07],...
    'string',' default',...
    'ForeGroundColor','black',...
    'callback',...
        ['if strcmp(questdlg(''do you really want to restore default options for clic corrections?''),''Yes'');',...
             'eval(get(windows.ClicCorrectionControl.cancel_handle,''CallBack''));',...%on clique sur cancel
             'restore_options(session);',...%on remet le fichier default_options.mat dans son etat d'origine
             'options_reloaded = load([session.HOME,session.SEP,''profilviewer'',session.SEP,''default_options.mat'']);',...%on le charge en memoire
             'session.options = rmfield(session, ''options'');',...
             'session.options = options_reloaded.racine;clear options_reloaded;',...
             'clic_correction_options;',...%on relance l'editeur d'options
             'set(windows.homefig.dlgbox,''string'',''clic corrections options restored successfully'',''ForeGroundColor'',[0,.6,0]);',...%message de confirmation
         'end;']);

     
     
     
%% II) structure creation options

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur sommet %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%II.1) recentrage_sommet : for activating the summit merging while creating a new structure
windows.ClicCorrectionControl.structurecreation.recentrage_sommet_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,14/15,.5,1/17],...
    'string','summit ',...
    'HorizontalAlignment','left');
windows.ClicCorrectionControl.structurecreation.recentrage_sommet_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,14/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_sommet,'on'));
%II.2) recentrage_sommet_units : units you want to use to define the summit merging distance
switch session.options.recentrage_sommet_units
    case {'pixels'}
        recentrage_sommet_choix=1;
%     case {'diag_percent'}
%         recentrage_sommet_choix=2;
%     case {'x_percent'}
%         recentrage_sommet_choix=3;
%     case {'z_percent'}
%         recentrage_sommet_choix=4;
end
windows.ClicCorrectionControl.structurecreation.recentrage_sommet_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,13/15,.45,1/17],...
    'string','summit merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.structurecreation.recentrage_sommet_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,13/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_sommet,...
    'value',recentrage_sommet_choix);
%II.3) recentrage_sommet_distance : merging distance when cliquing near from a already existing summit
windows.ClicCorrectionControl.structurecreation.recentrage_sommet_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,12/15,.45,1/17],...
    'string','summit merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.structurecreation.recentrage_sommet_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,12/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_sommet_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_sommet);





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur segment %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%II.4) recentrage_segment
windows.ClicCorrectionControl.structurecreation.recentrage_segment_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,11/15,.5,1/17],...
    'string','segment ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.structurecreation.recentrage_segment_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,11/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_segment,'on'));
%II.5) recentrage_segment_units : units you want to use to define the segment merging distance
switch session.options.recentrage_segment_units
    case {'pixels'}
        recentrage_segment_choix=1;
%     case {'diag_percent'}
%         recentrage_segment_choix=2;
%     case {'x_percent'}
%         recentrage_segment_choix=3;
%     case {'z_percent'}
%         recentrage_segment_choix=4;
end
windows.ClicCorrectionControl.structurecreation.recentrage_segment_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,10/15,.45,1/17],...
    'string','segment merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.structurecreation.recentrage_segment_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,10/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_segment,...
    'value',recentrage_segment_choix);
%II.6) recentrage_segment_distance : merging distance when cliquing near from a already existing segment
windows.ClicCorrectionControl.structurecreation.recentrage_segment_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,9/15,.45,1/17],...
    'string','segment merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.structurecreation.recentrage_segment_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,9/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_segment_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_segment);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur bords   %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%II.7) recentrage_bords
windows.ClicCorrectionControl.structurecreation.recentrage_bords_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,8/15,.5,1/17],...
    'string','boundaries ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.structurecreation.recentrage_bords_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,8/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_bords,'on'));
%II.8) recentrage_bords_units
switch session.options.recentrage_bords_units
    case {'pixels'}
        recentrage_bords_choix=1;
%     case {'diag_percent'}
%         recentrage_bords_choix=2;
%     case {'x_percent'}
%         recentrage_bords_choix=3;
%     case {'z_percent'}
%         recentrage_bords_choix=4;
end
windows.ClicCorrectionControl.structurecreation.recentrage_bords_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,7/15,.45,1/17],...
    'string','boundaries merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.structurecreation.recentrage_bords_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,7/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_bords,...
    'value',recentrage_bords_choix);
%II.9) recentrage_bords_distance : merging distance when cliquing near from
windows.ClicCorrectionControl.structurecreation.recentrage_bords_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,6/15,.45,1/17],...
    'string','boundaries merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.structurecreation.recentrage_bords_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,6/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_bords_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_bords);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur top     %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%II.10) recentrage_top
windows.ClicCorrectionControl.structurecreation.recentrage_top_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,5/15,.5,1/17],...
    'string','top ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.structurecreation.recentrage_top_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,5/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_top,'on'));
%II.11) recentrage_top_units
switch session.options.recentrage_top_units
    case {'pixels'}
        recentrage_top_choix=1;
%     case {'diag_percent'}
%         recentrage_top_choix=2;
%     case {'x_percent'}
%         recentrage_top_choix=3;
%     case {'z_percent'}
%         recentrage_top_choix=4;
end
windows.ClicCorrectionControl.structurecreation.recentrage_top_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,4/15,.45,1/17],...
    'string','top merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.structurecreation.recentrage_top_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,4/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_top,...
    'value',recentrage_top_choix);
%II.12) recentrage_top_distance : merging distance when cliquing near from 
windows.ClicCorrectionControl.structurecreation.recentrage_top_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,3/15,.45,1/17],...
    'string','top merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.structurecreation.recentrage_top_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,3/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_top_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_top);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur bottom  %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%II.13) recentrage_bottom
windows.ClicCorrectionControl.structurecreation.recentrage_bottom_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,2/15,.5,1/17],...
    'string','bottom ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.structurecreation.recentrage_bottom_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,2/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_bottom,'on'));
%II.14) recentrage_bottom_units
switch session.options.recentrage_bottom_units
    case {'pixels'}
        recentrage_bottom_choix=1;
%     case {'diag_percent'}
%         recentrage_bottom_choix=2;
%     case {'x_percent'}
%         recentrage_bottom_choix=3;
%     case {'z_percent'}
%         recentrage_bottom_choix=4;
end
windows.ClicCorrectionControl.structurecreation.recentrage_bottom_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,1/15,.45,1/17],...
    'string','bottom merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.structurecreation.recentrage_bottom_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,1/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_bottom,...
    'value',recentrage_bottom_choix);
%II.15) recentrage_segment_distance : merging distance when cliquing near from
windows.ClicCorrectionControl.structurecreation.recentrage_bottom_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,0/15,.45,1/17],...
    'string','bottom merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.structurecreation.recentrage_bottom_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.structurecreation.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,0/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_bottom_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_bottom);

%% III) move point options
%ICI%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur sommet %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%III.1) recentrage_deplacement_sommet : for activating the summit merging while moving a new structure
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,14/15,.5,1/17],...
    'string','summit ',...
    'HorizontalAlignment','left');
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,14/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_deplacement_sommet,'on'));
%III.2) recentrage_deplacement_sommet_units : units you want to use to define the summit merging distance
switch session.options.recentrage_deplacement_sommet_units
    case {'pixels'}
        recentrage_deplacement_sommet_choix=1;
%     case {'diag_percent'}
%         recentrage_deplacement_sommet_choix=2;
%     case {'x_percent'}
%         recentrage_deplacement_sommet_choix=3;
%     case {'z_percent'}
%         recentrage_deplacement_sommet_choix=4;
end
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,13/15,.45,1/17],...
    'string','summit merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,13/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_deplacement_sommet,...
    'value',recentrage_deplacement_sommet_choix);
%III.3) recentrage_deplacement_sommet_distance : merging distance when cliquing near from a already existing summit
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,12/15,.45,1/17],...
    'string','summit merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,12/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_deplacement_sommet_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_deplacement_sommet);





%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur segment %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%III.4) recentrage_deplacement_segment
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,11/15,.5,1/17],...
    'string','segment ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,11/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_deplacement_segment,'on'));
%III.5) recentrage_deplacement_segment_units : units you want to use to define the segment merging distance
switch session.options.recentrage_deplacement_segment_units
    case {'pixels'}
        recentrage_deplacement_segment_choix=1;
%     case {'diag_percent'}
%         recentrage_deplacement_segment_choix=2;
%     case {'x_percent'}
%         recentrage_deplacement_segment_choix=3;
%     case {'z_percent'}
%         recentrage_deplacement_segment_choix=4;
end
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,10/15,.45,1/17],...
    'string','segment merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,10/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_deplacement_segment,...
    'value',recentrage_deplacement_segment_choix);
%III.6) recentrage_deplacement_segment_distance : merging distance when cliquing near from a already existing segment
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,9/15,.45,1/17],...
    'string','segment merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,9/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_deplacement_segment_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_deplacement_segment);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur bords   %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%III.7) recentrage_deplacement_bords
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,8/15,.5,1/17],...
    'string','boundaries ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,8/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_deplacement_bords,'on'));
%III.8) recentrage_deplacement_bords_units
switch session.options.recentrage_deplacement_bords_units
    case {'pixels'}
        recentrage_deplacement_bords_choix=1;
%     case {'diag_percent'}
%         recentrage_deplacement_bords_choix=2;
%     case {'x_percent'}
%         recentrage_deplacement_bords_choix=3;
%     case {'z_percent'}
%         recentrage_deplacement_bords_choix=4;
end
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,7/15,.45,1/17],...
    'string','boundaries merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,7/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_deplacement_bords,...
    'value',recentrage_deplacement_bords_choix);
%III.9) recentrage_deplacement_bords_distance : merging distance when cliquing near from
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,6/15,.45,1/17],...
    'string','boundaries merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,6/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_deplacement_bords_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_deplacement_bords);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur top     %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%III.10) recentrage_deplacement_top
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,5/15,.5,1/17],...
    'string','top ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,5/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_deplacement_top,'on'));
%III.11) recentrage_deplacement_top_units
switch session.options.recentrage_deplacement_top_units
    case {'pixels'}
        recentrage_deplacement_top_choix=1;
%     case {'diag_percent'}
%         recentrage_deplacement_top_choix=2;
%     case {'x_percent'}
%         recentrage_deplacement_top_choix=3;
%     case {'z_percent'}
%         recentrage_deplacement_top_choix=4;
end
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,4/15,.45,1/17],...
    'string','top merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,4/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_deplacement_top,...
    'value',recentrage_deplacement_top_choix);
%III.12) recentrage_deplacement_top_distance : merging distance when cliquing near from 
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,3/15,.45,1/17],...
    'string','top merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,3/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_deplacement_top_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_deplacement_top);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% recentrage sur bottom  %%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%III.13) recentrage_deplacement_bottom
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_text  =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[0,2/15,.5,1/17],...
    'string','bottom ',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','r')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_chkbx =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','checkbox',...
    'units','normalized',...
    'position',[.55,2/15,.1,1/15],...
    'value',strcmp(session.options.recentrage_deplacement_bottom,'on'));
%III.14) recentrage_deplacement_bottom_units
switch session.options.recentrage_deplacement_bottom_units
    case {'pixels'}
        recentrage_deplacement_bottom_choix=1;
%     case {'diag_percent'}
%         recentrage_deplacement_bottom_choix=2;
%     case {'x_percent'}
%         recentrage_deplacement_bottom_choix=3;
%     case {'z_percent'}
%         recentrage_deplacement_bottom_choix=4;
end
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_units_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...
    'style','text',...
    'units','normalized',...
    'position',[.05,1/15,.45,1/17],...
    'string','bottom merging distance unit',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','g')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_units_popup =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','popup',...
    'units','normalized',...    
    'position',[.55,1/15,.45,1/15],...   
    'string','pixels',...
    'enable',session.options.recentrage_deplacement_bottom,...
    'value',recentrage_deplacement_bottom_choix);
%III.15) recentrage_deplacement_segment_distance : merging distance when cliquing near from
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_distance_text =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','text',...
    'units','normalized',...
    'position',[.05,0/15,.45,1/17],...
    'string','bottom merging distance',...
    'HorizontalAlignment','left');%,...
%    'backgroundcolor','b')
windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_distance_edit =uicontrol(...
    'parent',windows.ClicCorrectionControl.movingpoints.panelhandle,...    
    'style','edit',...
    'units','normalized',...    
    'position',[.55,0/15,.4,1/17],...   
    'string',num2str(session.options.recentrage_deplacement_bottom_distance),...
    'HorizontalAlignment','right',...
    'enable',session.options.recentrage_deplacement_bottom);
%ICI%


%% Callbacks : on attend d'avoir généré tous les panels pour pouvoir attribuer les callbacks

 %% Callbacks de checkbox
%II.1
set(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_chkbx,''value'')==1;',...
                    'session.options.recentrage_sommet=''on'';',...
                'else;',...
                    'session.options.recentrage_sommet=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_units_popup  ,''enable'',session.options.recentrage_sommet);',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_distance_edit,''enable'',session.options.recentrage_sommet);']);
%II.4
set(windows.ClicCorrectionControl.structurecreation.recentrage_segment_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.structurecreation.recentrage_segment_chkbx,''value'')==1;',...
                    'session.options.recentrage_segment=''on'';',...
                'else;',...
                    'session.options.recentrage_segment=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_segment_units_popup  ,''enable'',session.options.recentrage_segment);',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_segment_distance_edit,''enable'',session.options.recentrage_segment);']);
%II.7
set(windows.ClicCorrectionControl.structurecreation.recentrage_bords_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.structurecreation.recentrage_bords_chkbx,''value'')==1;',...
                    'session.options.recentrage_bords=''on'';',...
                'else;',...
                    'session.options.recentrage_bords=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_bords_units_popup  ,''enable'',session.options.recentrage_bords);',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_bords_distance_edit,''enable'',session.options.recentrage_bords);']);
%II.10
set(windows.ClicCorrectionControl.structurecreation.recentrage_top_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.structurecreation.recentrage_top_chkbx,''value'')==1;',...
                    'session.options.recentrage_top=''on'';',...
                'else;',...
                    'session.options.recentrage_top=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_top_units_popup  ,''enable'',session.options.recentrage_top);',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_top_distance_edit,''enable'',session.options.recentrage_top);']);
set(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_chkbx,''value'')==1;',...
                    'session.options.recentrage_bottom=''on'';',...
                'else;',...
                    'session.options.recentrage_bottom=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_units_popup  ,''enable'',session.options.recentrage_bottom);',...
                'set(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_distance_edit,''enable'',session.options.recentrage_bottom);']);
%ICI%
%III.1
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_chkbx,''value'')==1;',...
                    'session.options.recentrage_deplacement_sommet=''on'';',...
                'else;',...
                    'session.options.recentrage_deplacement_sommet=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_units_popup  ,''enable'',session.options.recentrage_deplacement_sommet);',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_distance_edit,''enable'',session.options.recentrage_deplacement_sommet);']);
%III.4
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_chkbx,''value'')==1;',...
                    'session.options.recentrage_deplacement_segment=''on'';',...
                'else;',...
                    'session.options.recentrage_deplacement_segment=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_units_popup  ,''enable'',session.options.recentrage_deplacement_segment);',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_distance_edit,''enable'',session.options.recentrage_deplacement_segment);']);
%III.7
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_chkbx,''value'')==1;',...
                    'session.options.recentrage_deplacement_bords=''on'';',...
                'else;',...
                    'session.options.recentrage_deplacement_bords=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_units_popup  ,''enable'',session.options.recentrage_deplacement_bords);',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_distance_edit,''enable'',session.options.recentrage_deplacement_bords);']);
%III.10
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_chkbx,''value'')==1;',...
                    'session.options.recentrage_deplacement_top=''on'';',...
                'else;',...
                    'session.options.recentrage_deplacement_top=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_units_popup  ,''enable'',session.options.recentrage_deplacement_top);',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_distance_edit,''enable'',session.options.recentrage_deplacement_top);']);
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_chkbx,...
    'callback',['if get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_chkbx,''value'')==1;',...
                    'session.options.recentrage_deplacement_bottom=''on'';',...
                'else;',...
                    'session.options.recentrage_deplacement_bottom=''off'';',...
                'end;',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_units_popup  ,''enable'',session.options.recentrage_deplacement_bottom);',...
                'set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_distance_edit,''enable'',session.options.recentrage_deplacement_bottom);']);
%ICI%

            
 %% callbacks de popups
popuplist={'profil'};%,'diag_percent','x_percent','z_percent'};
%II.2
set(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_units_popup,...
    'callback','session.options.recentrage_sommet_units=popuplist{get(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_units_popup,''value'')};');
%II.5
set(windows.ClicCorrectionControl.structurecreation.recentrage_segment_units_popup,...
    'callback','session.options.recentrage_segment_units=popuplist{get(windows.ClicCorrectionControl.structurecreation.recentrage_segment_units_popup,''value'')};');
%II.8
set(windows.ClicCorrectionControl.structurecreation.recentrage_bords_units_popup,...
    'callback','session.options.recentrage_bords_units=popuplist{get(windows.ClicCorrectionControl.structurecreation.recentrage_bords_units_popup,''value'')};');
%II.11
set(windows.ClicCorrectionControl.structurecreation.recentrage_top_units_popup,...
    'callback','session.options.recentrage_top_units=popuplist{get(windows.ClicCorrectionControl.structurecreation.recentrage_top_units_popup,''value'')};');
%II.14
set(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_units_popup,...
    'callback','session.options.recentrage_bottom_units=popuplist{get(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_units_popup,''value'')};');
%%%
%ICI%
%III.2
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_units_popup,...
    'callback','session.options.recentrage_deplacement_sommet_units=popuplist{get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_units_popup,''value'')};');
%III.5
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_units_popup,...
    'callback','session.options.recentrage_deplacement_segment_units=popuplist{get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_units_popup,''value'')};');
%III.8
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_units_popup,...
    'callback','session.options.recentrage_deplacement_bords_units=popuplist{get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_units_popup,''value'')};');
%III.11
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_units_popup,...
    'callback','session.options.recentrage_deplacement_top_units=popuplist{get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_units_popup,''value'')};');
%III.14
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_units_popup,...
    'callback','session.options.recentrage_deplacement_bottom_units=popuplist{get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_units_popup,''value'')};');
%ICI%

%% callbacks de edit
% II.3
set(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_distance_edit,...
    'callback','session.options.recentrage_sommet_distance=str2num(get(windows.ClicCorrectionControl.structurecreation.recentrage_sommet_distance_edit,''string''));');
% II.6
set(windows.ClicCorrectionControl.structurecreation.recentrage_segment_distance_edit,...
    'callback','session.options.recentrage_segment_distance=str2num(get(windows.ClicCorrectionControl.structurecreation.recentrage_segment_distance_edit,''string''));');
% II.9
set(windows.ClicCorrectionControl.structurecreation.recentrage_bords_distance_edit,...
    'callback','session.options.recentrage_bords_distance=str2num(get(windows.ClicCorrectionControl.structurecreation.recentrage_bords_distance_edit,''string''));');
% II.12
set(windows.ClicCorrectionControl.structurecreation.recentrage_top_distance_edit,...
    'callback','session.options.recentrage_top_distance=str2num(get(windows.ClicCorrectionControl.structurecreation.recentrage_top_distance_edit,''string''));');
% II.15
set(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_distance_edit,...
    'callback','session.options.recentrage_bottom_distance=str2num(get(windows.ClicCorrectionControl.structurecreation.recentrage_bottom_distance_edit,''string''));');
%ICI%
% III.3
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_distance_edit,...
    'callback','session.options.recentrage_deplacement_sommet_distance=str2num(get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_sommet_distance_edit,''string''));');
% III.6
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_distance_edit,...
    'callback','session.options.recentrage_deplacement_segment_distance=str2num(get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_segment_distance_edit,''string''));');
% III.9
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_distance_edit,...
    'callback','session.options.recentrage_deplacement_bords_distance=str2num(get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bords_distance_edit,''string''));');
% III.12
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_distance_edit,...
    'callback','session.options.recentrage_deplacement_top_distance=str2num(get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_top_distance_edit,''string''));');
% III.15
set(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_distance_edit,...
    'callback','session.options.recentrage_deplacement_bottom_distance=str2num(get(windows.ClicCorrectionControl.movingpoints.recentrage_deplacement_bottom_distance_edit,''string''));');
%ICI%

%% cleaning the workspace
%clear options_saved : NON!!!, une partie des variables temporaire doit etre concervee tant que la fenetre de control est ouverte,cf deletefvn pour leur supression!!!
clear recentrage_bords_choix recentrage_bottom_choix recentrage_deplacement_bords_choix recentrage_deplacement_bottom_choix recentrage_deplacement_top_choix recentrage_segment_choix recentrage_sommet_choix recentrage_top_choix recentrage_deplacement_segment_choix recentrage_deplacement_sommet_choix 



