function gravmanager1_2(varargin)

try
    windows = evalin('base', 'windows;');
    if strcmpi(questdlg(sprintf('gravmanager %s is already running, \nforce quit and restart ? \n!!! ALL UNSAVED DATA WILL BE LOST !!!?', evalin('base','session.VERSION;'))),'Yes')
        close all force
    else
        return
    end
end

evalin('base','clear all;close all')
evalin('base','main_gravmanager1_2;')
if nargin >=1
    evalin('base',['session.infile = ''',varargin{1},''';',...
                 '[profil.xmax,profil.model,erreur]=read_in(session.infile);',...
                     'if erreur;errordlg([''cannot open infile '',session.infile]);',...
                     'else;',...
                         'profil.zmin=[];',...
                         'profil.zmax=[];',...
                         'profil.units=''km'';',...
                         'profil=refresh_profil(windows,profil,''all'');',...
                         'set(windows.homefig.handle,''name'',session.infile);',...
                         'set(windows.homefig.menu.Tools.parent,''enable'',''on'');',...
                         'set(windows.homefig.menu.Objects.parent,''enable'',''on'');',...
                         'set(windows.homefig.menu.Edit.parent,''enable'',''on'');',...
                     'end;clear erreur'])
end