clc
getHOME;
%% WELCOME
fprintf('-----------------------------------------------------\n');
fprintf('   gravlab : gravimetric model builder           \n');
fprintf('   version %3s                                       \n',session.VERSION);
fprintf('   M.Lehujeur, Strasbourg University                 \n');
   disp('   <a href="">lehujeur@unistra.fr</a>');
fprintf('   11-03-2012                                        \n');
fprintf('-----------------------------------------------------\n');

%% conventions : 
%l'axe des z est vers le haut.
%quand on parle d un polygone le dernier sommet est = au premier et est
       %compté comme un sommet a part entiere



%% gestion des fenetres de travail
windows.homefig.handle=figure();
windows.prtfig.handle=[];%figure pour les impressions



%% gestion des parametre de la session
session.saved=1;
session.infile=[];
inicurves;
session.xyzfile=[];
if strcmp(computer,'PCWIN')
    session.SEP='\';
else
    session.SEP='/';
end

try
    %options telles qu'elles étaient lors du dernier lancement
    options_reloaded=load([session.HOME,session.SEP,'profilviewer',session.SEP,'default_options.mat']);
catch
    %si on ne trouve pas le fichier, on est obligé de le recréer a partir des options par defaut
    warndlg(sprintf('unable to detect file \n"%s"\nfrom last use\nrestore default options',[session.HOME,session.SEP,'profilviewer',session.SEP,'default_options.mat']))
    restore_options(session);
    options_reloaded=load([session.HOME,session.SEP,'profilviewer',session.SEP,'default_options.mat']);
end
session.options=options_reloaded.racine;



%% affichage de la fenetre principale 
set(windows.homefig.handle,'units','normalized',...
                    'position',[0.0016    0.0413    0.5000    0.5000],...
                    'menubar','none',...
                    'name','profilviewer',...
                    'numbertitle','off',...
                    'closerequestfcn','quit_gravlab;')

%% menus :
%1) File
windows.homefig.menu.File.parent=uimenu('label','File');
    windows.homefig.menu.File.new=uimenu(windows.homefig.menu.File.parent,...
                                'label','new model',...
                                'callback','new_in',...
                                'accelerator','N');
    windows.homefig.menu.File.open=uimenu(windows.homefig.menu.File.parent,...
                                'label','open...',...
                                'callback','open_in_Xz_xyz',...
                                'accelerator','O');                                
    windows.homefig.menu.File.saveas=uimenu(windows.homefig.menu.File.parent,...
                                'label','save as...',...
                                'callback','save_in;',...
                                'accelerator','S');        
    windows.homefig.menu.File.quit=uimenu(windows.homefig.menu.File.parent,...
                                'label','quit',...
                                'callback','quit_gravlab;',...
                                'accelerator','Q',...
                                'separator','on');
%2) Objects
windows.homefig.menu.Objects.parent=uimenu('label','Objects',...
                                      'enable','off');
    windows.homefig.menu.Objects.new=uimenu(windows.homefig.menu.Objects.parent,...
                                 'label','new structure',...
                                 'callback','new_struct;');
    windows.homefig.menu.Objects.modify.parent=uimenu(windows.homefig.menu.Objects.parent,...
                                 'label','modify...');
        windows.homefig.menu.Objects.modify.position=uimenu(windows.homefig.menu.Objects.modify.parent,...
                                 'label','positions',...
                                 'callback','move_in;');
        windows.homefig.menu.Objects.modify.addpoints=uimenu(windows.homefig.menu.Objects.modify.parent,...
                                 'label','add points','enable','off',...
                                 'callback','add_points');
        windows.homefig.menu.Objects.modify.rmpoints=uimenu(windows.homefig.menu.Objects.modify.parent,...
                                 'label','remove points','enable','off',...
                                 'callback','remove_points');
%2.5) Edit
windows.homefig.menu.Edit.parent=uimenu('label','Edit',...
                                      'enable','off');
    windows.homefig.menu.Edit.properties=uimenu(windows.homefig.menu.Edit.parent,...
                                 'label','properties...',...
                                 'callback','[profil,session]=edit_profil_properties(windows,session,profil);');
    windows.homefig.menu.Edit.showlinks.parent=uimenu(windows.homefig.menu.Edit.parent,...
                                'label','links','enable','on',...
                                'callback','show_links;');
    windows.homefig.menu.Tools.dimensions=uimenu(windows.homefig.menu.Edit.parent,...
                                'label','dimensions',...
                                'callback','change_dimensions');
    
%3) Tools                        
windows.homefig.menu.Tools.parent=uimenu('label','Tools',...
                                      'enable','off');
    windows.homefig.menu.Tools.zoom.parent=uimenu(windows.homefig.menu.Tools.parent,...
                                'label','zoom');
        windows.homefig.menu.Tools.zoom.zoom=uimenu(windows.homefig.menu.Tools.zoom.parent,...                    
                                'callback','profil_zoom',...
                                'label','zoom');
        windows.homefig.menu.Tools.zoom.mooz=uimenu(windows.homefig.menu.Tools.zoom.parent,...                    
                                'callback','profil_mooz',...
                                'label','mooz');%'enable','off'
    windows.homefig.menu.Tools.curveviewer.parent=uimenu(windows.homefig.menu.Tools.parent,...
                                'label','curveviewer','callback','main_curveviewer1_1;');
    windows.homefig.menu.Tools.mapviewer.parent=uimenu(windows.homefig.menu.Tools.parent,...
                                'label','mapviewer','callback','main_mapviewer;');
    windows.homefig.menu.Tools.volumeviewer.parent=uimenu(windows.homefig.menu.Tools.parent,...
                                'label','volumeviewer','callback',...
                                ['helpdlg(''The volumeviewer is not ready for now, future version should look like this...'');',...
                                 'open([session.HOME,session.SEP,''volumeviewer'', session.SEP, ''pub.fig''])']);
%4) Options
windows.homefig.menu.Options.parent=uimenu('label','Options',...
                                      'enable','on');
    windows.homefig.menu.Options.merging=uimenu(windows.homefig.menu.Options.parent,...
                                'label','clic corrections',...
                                'callback','clic_correction_options');%'errordlg(''not available now'')');
%boite de dialogue
windows.homefig.dlgbox=uictrl1_1('style','edit',...
                                 'units','normalized',...
                                 'position',[0,0,.7,.04],...
                                 'ForegroundColor','k',...
                                 'HorizontalAlignment','left',...
                                 'string','message box',...
                                 'lowerleftxposition', 'normalized',...
                                 'upperrightxposition', 'normalized');
windows.homefig.dlgbox1=uictrl1_1('style','edit',...
                                 'units','normalized',...
                                 'position',[.7,0,.15,.04],...
                                 'ForegroundColor','k',...
                                 'HorizontalAlignment','left',...
                                 'lowerleftxposition', 'normalized',...                                 
                                 'upperrightxposition', 'normalized');
windows.homefig.dlgbox2=uictrl1_1('style','edit',...
                                 'units','normalized',...
                                 'position',[.85,0,.15,.04],...
                                 'ForegroundColor','k',...
                                 'HorizontalAlignment','left',...
                                 'lowerleftxposition', 'normalized',...
                                 'upperrightxposition', 'normalized');
%% cursors
windows.homefig.curvecursor.handle=plot(0,0, 'k.', 'visible','off');
set(gca, 'visible', 'off')
%% cleaning the workspace
clear options_reloaded i