%open_in_Xz_xyz

%% create the control figure
windows.opencontrol.handle=figure();
set(windows.opencontrol.handle,'units','normalized',...
               'menubar','none',...
               'name','select your files',...
               'position',[0.2578    0.4725    0.5016    0.2188])

%% panels 
%1) panel for infile
windows.opencontrol.inpanel_handle=uipanel(...
    'title','model (.in)',...
    'Fontsize',10,...
    'units','normalized',...
    'position',[0,3/4,1,1/4]);

% %2) panel for Xzfile
% windows.opencontrol.Xzpanel_handle=uipanel(...
%     'title','anomaly curve (.Xz)',...
%     'Fontsize',10,...
%     'units','normalized',...
%     'position',[0,1/2,1,1/4]);
% 
% %3) panel for xyzfile
% windows.opencontrol.xyzpanel_handle=uipanel(...
%     'title','anomaly map (.xyz)',...
%     'Fontsize',10,...
%     'units','normalized',...
%     'position',[0,1/4,1,1/4]);

%4) validation controls (ok cancel)
    %4.1) ok
          %callback -> regarde si le field .in est ok sinon erreur
          %         -> si oui, lecture du .in
          %         -> rafraichissement du profil
windows.opencontrol.ok_handle=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'string','ok',...
    'Fontsize',10,...
    'position',[.2,.02,.1,1/4-2*.02],...
    'callback',...
               ['if ~isinok;',...
                     'errordlg(''cannot open this .in file'');',...
                'else;',...
                     'session.infile=opentmp.infile;',...
                     'set(windows.homefig.handle,''name'',session.infile);',...
                     '[profil.xmax,profil.model]=read_in(session.infile);',...
                     'profil.zmin=[];',...
                     'profil.zmax=[];',...
                     'profil.units=''km'';',...
                     'close(windows.opencontrol.handle);',...
                     'profil=refresh_profil(windows,profil,''all'');',...
                     'windows=rmfield(windows,''opencontrol'');',...
                     'set(windows.homefig.menu.Tools.parent,''enable'',''on'');',...
                     'set(windows.homefig.menu.Objects.parent,''enable'',''on'');',...
                     'set(windows.homefig.menu.Edit.parent,''enable'',''on'');',...
                     'set(windows.homefig.menu.File.open,''enable'',''off'');',...
                     'set(windows.homefig.menu.File.new,''enable'',''off'');',...
                     'clear isinok opentmp;',...
                'end;']);
    %4.2) Cancel
windows.opencontrol.cancel_handle=uicontrol(...
    'style','pushbutton',...
    'units','normalized',...
    'string','cancel',...
    'Fontsize',10,...
    'position',[.7,.02,.1,1/4-2*.02],...
    'callback','clear opentmp isinok;close(windows.opencontrol.handle);windows=rmfield(windows,''opencontrol'');');

%% infile
isinok=0;
windows.opencontrol.inname_handle=uicontrol(...
    'parent',windows.opencontrol.inpanel_handle,...
    'style','edit',...
    'units','normalized',...
    'position',[1/6,0,5/6,1],...
    'HorizontalAlignment','left');
windows.opencontrol.inbrowse_handle=uicontrol(...
    'parent',windows.opencontrol.inpanel_handle,...
    'style','pushbutton',...
    'units','normalized',...
    'position',[0,0,1/6,1],...
    'string','browse',...
    'callback',...
               ['[Filename,Pathname]=uigetfile(''*.in'');',...
                'if Filename==0 & Pathname==0;',...
                     'clear Filename Pathname;',...
                'else;',...
                     'opentmp.infile=[Pathname,Filename];',...
                     'set(windows.opencontrol.inname_handle,''string'',opentmp.infile,''Foregroundcolor'',[0 .7 0]);',...
                     'isinok=1;',...
                'end;',...
                'clear Filename Pathname;']);
set(windows.opencontrol.inname_handle,...
    'callback',...
              ['fid=fopen(get(windows.opencontrol.inname_handle,''string''),''r'');',...
               'if fid==-1;',...
                   'set(windows.opencontrol.inname_handle,''Foregroundcolor'',[.7 0 0]);',...
                   'isinok=0;',...
               'else;',...
                   'opentmp.infile=get(windows.opencontrol.inname_handle,''string'');',...
                   'set(windows.opencontrol.inname_handle,''Foregroundcolor'',[0 .7 0]);',...
                   'isinok=1;',...
                   'fclose(fid);',...
               'end;',...
               'clear fid ans'])

if ~isempty(session.infile)
    set(windows.opencontrol.inname_handle,...
        'string',session.infile,...
        'Foregroundcolor',[0 .7 0]);
else
    set(windows.opencontrol.inname_handle,...
        'string',pwd,...
        'enable','on',...
        'Foregroundcolor',[.7 0 0]);
end
