% show_links

%si il n'y a pas de structures
if isempty(profil.model)
    errordlg('no structures found')
    return
end

%% blockage de toute autre action
fields=fieldnames(windows.homefig.menu);
for field=1:length(fields)
    set(windows.homefig.menu.(fields{field}).parent,'enable','off')
end

%% blockage des structures 
block_structures(profil);%le deblockage se faira avec refresh_profil

%% boutton de fin de fonction
endbutton=uimenu('label','|   ok',...
    'callback','hide_links;');
            
%% show ici
scattlinks=find_links(profil,'sommet');
% Islinked = [];Isautolinked=[];
% for nstr = 1 : length(profil.model)
%     for nsom = 1 : profil.model(nstr).n
%         [Nlinks, Autolink] = howmanylinks(nstr,nsom, scattlinks);
%         Islinked = [ Islinked ; logical(Nlinks)];
%         Isautolinked = [ Isautolinked ; logical(Autolink)];
%     end
% end
Islinked = ~isnan(scattlinks(:,5));
Isautolinked = logical(scattlinks(:,16));
Ia =  Islinked & ~Isautolinked;
Id =  Islinked &  Isautolinked;
Ib = ~Islinked & ~Isautolinked;
Ic = ~Islinked &  Isautolinked;


% LINKED AND NOT AUTOLINKED
    %quand je clique sur un point appartenant à a.plot_handle, 
    %le callback ButtondownFcn attribue a a.requestedpoint le numéro du
    %sommet sur lequel on vient de cliqué et sera réutilisé par le context
    %menu
a.RightClic.parent=uicontextmenu;
a.RightClic.infos=uimenu(a.RightClic.parent,...
    'label','infos',...
    'callback',['str = sprintf(''\n\n(%.2f,  %.2f)    is a link between :\n'',a.requestedpoint.coo(1,1),a.requestedpoint.coo(1,2));',...
                'plottmp = plot(a.requestedpoint.coo(1), a.requestedpoint.coo(2),''rs'');',...
                'for i = 1 :length(a.requestedpoint.nstr);',...
                '    filltmp(i)=fill(profil.model(a.requestedpoint.nstr(i)).polyg(:,1), profil.model(a.requestedpoint.nstr(i)).polyg(:,2), zeros(size(profil.model(a.requestedpoint.nstr(i)).polyg,1),1),''facecolor'', ''b'',''facealpha'',.1);',...
                '    str=[str,sprintf(''   structure %d (%s) summit %d\n'',a.requestedpoint.nstr(i),profil.model(a.requestedpoint.nstr(i)).name,a.requestedpoint.nsom(i))];',...
                'end;',...
                'set(endbutton,''enable'',''off'');',...
                'helpdlgwait([str,sprintf(''\n\n.'')]);',...
                'for i = 1 :length(a.requestedpoint.nstr);',...
                '    set(filltmp(i),''visible'',''off'');',...
                'end;',...
                'set(endbutton,''enable'',''on'');',...
                'set(plottmp,''visible'',''off'');',...
                'clear i str filltmp plottmp']);
a.RightClic.breaklink=uimenu(a.RightClic.parent,...
    'label','break link',...
    'callback',['break_link(a.requestedpoint.nstr(1), a.requestedpoint.nsom(1));',...%modification du profil avec evalin
                'if session.saved;',...
                '   session.saved = 0;',...
                '   set(windows.homefig.handle,''name'',[get(windows.homefig.handle,''name''),''*'']);',...
                'end;',...
                'hide_links;show_links;']);%redémarage de l'éditeur de lien
            
a.requestedpoint = [];
a.plot_handle = plot(scattlinks(Ia,3),...
         scattlinks(Ia,4),'s',...
         'markerfacecolor','g',...         'visible','off',...
         'markeredgecolor','k',...
         'uicontextmenu',a.RightClic.parent,...
         'ButtondownFcn',['cp = get(gca, ''currentpoint'');',...                     %recuperation des coo du clic droit
                          'Dpx = Dscattclicpx(cp(1,1:2),scattlinks(Ia,3:4),gca);',...%distance entre le clic est les sommets indiqués par Ia
                          'IDpx = Dpx==min(Dpx);',...                                %parmis les Ia on cherche celui qui est le + proche du clic
                          'Iaval = find(Ia);',...                                    %conversion indexation bouléenne en indexation double
                          'Iaa = Iaval(IDpx);',...                                   %récupération des lignes de scattlinks concernées 
                          'Iaa = [Iaa(1), scattlinks(Iaa(1),5:15)]'';',...           %ajout des sommets liés à ce point
                          'Iaa(isnan(Iaa))=[];',...                                  %supression des NaNs
                          'a.requestedpoint.nstr = scattlinks( Iaa ,1);',...
                          'a.requestedpoint.nsom = scattlinks( Iaa ,2);',...
                          'a.requestedpoint.coo = scattlinks( Iaa, 3:4);',...                          
                          'clear cp Dpx IDpx Iaval Iaa']);
%  LINKED AND AUTOLINKED
d.plot_handle  = plot(scattlinks(Id,3),...
         scattlinks(Id,4),'s',...
         'markerfacecolor','y',...         'visible','off',...
         'markeredgecolor','k');
b.plot_handle  = plot(scattlinks(Ib,3),...
         scattlinks(Ib,4),'o',...
         'markerfacecolor','g',...
         'markeredgecolor','k');
c.plot_handle  = plot(scattlinks(Ic,3),...
         scattlinks(Ic,4),'o',...
         'markerfacecolor','y',...
         'markeredgecolor','k');   


set(windows.homefig.dlgbox,...
    'Foregroundcolor','k',...
    'string','squares/circles = linked/not linked | yellow/green = autolinked/not autolinked');


%% clean up
clear nstr nsom Nlinks Autolink  field fields  Islinked Isautolinked %Ia  scattlinks
