%main_mapviewer : 
% main application for maps in gravlab,
% the program is disgned such as 
% the mapviewer can be run as a child application of gravlab or 
% independently

%% OPEN MAPVIEWER
try
    if ~isempty( windows.mapfig.handle )
        try 
            figure(windows.mapfig.handle)
            return
        catch
            windows.mapfig.handle = [];
        end
    end
end

windows.mapfig.handle = figure(...
    'menubar', 'none',...
    'tag', 'mapfig',...
    'numbertitle','off', ...
    'name', 'mapviewer',...
    'closerequestfcn', 'quit_mapviewer;');
hold on;

%boites de dialogue
windows.mapfig.dlgbox=uictrl1_1('style','edit',...
                                 'units','normalized',...
                                 'position',[0,0,.7,.04],...
                                 'ForegroundColor','k',...
                                 'HorizontalAlignment','left',...
                                 'string','',...
                                 'tag', 'mapdlgbox',...
                                 'lowerleftxposition', 'normalized',...
                                 'upperrightxposition', 'normalized');
windows.mapfig.dlgbox1=uictrl1_1('style','edit',...
                                 'units','normalized',...
                                 'position',[.7,0,.15,.04],...
                                 'ForegroundColor','k',...
                                 'tag', 'mapdlgbox1',...
                                 'HorizontalAlignment','left',...
                                 'lowerleftxposition', 'normalized',...                                 
                                 'upperrightxposition', 'normalized');
windows.mapfig.dlgbox2=uictrl1_1('style','edit',...
                                 'units','normalized',...
                                 'position',[.85,0,.15,.04],...
                                 'ForegroundColor','k',...
                                 'tag', 'mapdlgbox2',...
                                 'HorizontalAlignment','left',...
                                 'lowerleftxposition', 'normalized',...
                                 'upperrightxposition', 'normalized');
                             
set(windows.mapfig.handle, 'WindowButtonMotionFcn',  'mapbuttonmotion')
refreshmap;

%% GENERATE TOOL BAR
windows.mapfig.menu.File.parent = uimenu('label', 'File');
    windows.mapfig.menu.File.open = uimenu(...
        'parent', windows.mapfig.menu.File.parent,...
        'label', 'Open',...
        'callback', 'openmap;');
    windows.mapfig.menu.File.quit = uimenu(...
        'parent', windows.mapfig.menu.File.parent,...
        'label', 'Quit',...
        'Separator','on',...
        'accelerator','Q',...
        'callback', 'quit_mapviewer;');
windows.mapfig.menu.Objects.parent = uimenu('label', 'Objects');
    windows.mapfig.menu.Objects.extractsection = uimenu(...
        'parent', windows.mapfig.menu.Objects.parent,...
        'label', 'new section...',...
        'callback', 'newsection;');
    
%% REPLOT IF DATA IN WORKSPACE
try
    if ~isempty(session.xyzfile.data.X)
        refreshmap;
        return
    end
end

%% WORKSPACE
session.xyzfile.file = [];
session.xyzfile.handle = [];
session.xyzfile.data.X = [];
session.xyzfile.data.Y = [];
session.xyzfile.data.Z = [];

